#pragma once

#include "GameManager.h"
#include "EliteMonState/Joker/Joker.h"


#include "EliteMonState/Joker/JokerState_Idle.h"
#include "EliteMonState/Joker/JokerState_ComboA1.h"
#include "EliteMonState/Joker/JokerState_ComboA2.h"
#include "EliteMonState/Joker/JokerState_ComboB1.h"
#include "EliteMonState/Joker/JokerState_ComboB2.h"
#include "EliteMonState/Joker/JokerState_Dead.h"
#include "EliteMonState/Joker/JokerState_Execution_End.h"
#include "EliteMonState/Joker/JokerState_Execution_Loop.h"
#include "EliteMonState/Joker/JokerState_Execution_Start.h"
#include "EliteMonState/Joker/JokerState_JumpAttack.h"
#include "EliteMonState/Joker/JokerState_RunAtkEnd.h"
#include "EliteMonState/Joker/JokerState_RunAtkLoop.h"
#include "EliteMonState/Joker/JokerState_RunAtkStart.h"
#include "EliteMonState/Joker/JokerState_Sp_Open.h"
#include "EliteMonState/Joker/JokerState_Stun_End.h"
#include "EliteMonState/Joker/JokerState_Stun_Loop.h"
#include "EliteMonState/Joker/JokerState_Stun_Start.h"
#include "EliteMonState/Joker/JokerState_TurnAtkL.h"
#include "EliteMonState/Joker/JokerState_TurnAtkR.h"
#include "EliteMonState/Joker/JokerState_TurnL90.h"
#include "EliteMonState/Joker/JokerState_TurnR90.h"
#include "EliteMonState/Joker/JokerState_WalkB.h"
#include "EliteMonState/Joker/JokerState_WalkF.h"
#include "EliteMonState/Joker/JokerState_WalkL.h"
#include "EliteMonState/Joker/JokerState_WalkR.h"
#include "EliteMonState/Joker/JokerState_WheelAtkEnd.h"
#include "EliteMonState/Joker/JokerState_WheelAtkEnd2.h"
#include "EliteMonState/Joker/JokerState_WheelAtkLoop.h"
#include "EliteMonState/Joker/JokerState_WheelAtkStart.h"
#include "EliteMonState/Joker/JokerState_StrongAttack.h"
#include "EliteMonState/Joker/JokerState_ShockAttack.h"

