#pragma once

#include "GameManager.h"


#include "NorMonState/NorMonState_Stop.h"
#include "NorMonState/NorMonState_Awake.h"
#include "NorMonState/NorMonState_Die.h"
#include "NorMonState/NorMonState_SitToIdle.h"
#include "NorMonState/NorMonState_Farry.h"
#include "NorMonState/NorMonState_GroggyEnd.h"
#include "NorMonState/NorMonState_GroggyLoop.h"
#include "NorMonState/NorMonState_GroggyStart.h"
#include "NorMonState/NorMonState_HeavyAttack1.h"
#include "NorMonState/NorMonState_HeavyAttack2.h"
#include "NorMonState/NorMonState_HeavyAttack3.h"
#include "NorMonState/NorMonState_HeavyAttack4.h"
#include "NorMonState/NorMonState_HeavyAttack5.h"
#include "NorMonState/NorMonState_HurtL.h"
#include "NorMonState/NorMonState_HurtR.h"
#include "NorMonState/NorMonState_Idle.h"
#include "NorMonState/NorMonState_LightAttack1.h"
#include "NorMonState/NorMonState_LightAttack2.h"
#include "NorMonState/NorMonState_LightAttack3.h"
#include "NorMonState/NorMonState_Run.h"
#include "NorMonState/NorMonState_SpecialAttackStart.h"
#include "NorMonState/NorMonState_SpecialAttackLoop.h"
#include "NorMonState/NorMonState_SpecialAttackEnd.h"
#include "NorMonState/NorMonState_TakeExecution.h"
#include "NorMonState/NorMonState_TurnL90.h"
#include "NorMonState/NorMonState_TurnR90.h"
#include "NorMonState/NorMonState_Walk_B.h"
#include "NorMonState/NorMonState_Walk_BL.h"
#include "NorMonState/NorMonState_Walk_BR.h"
#include "NorMonState/NorMonState_Walk_F.h"
#include "NorMonState/NorMonState_Walk_FL.h"
#include "NorMonState/NorMonState_Walk_FR.h"
#include "NorMonState/NorMonState_Walk_L.h"
#include "NorMonState/NorMonState_Walk_R.h"
#include "NorMonState/NorMonState_Parry.h"
#include "NorMonState/NorMonState_Petrol.h"
#include "NorMonState/NorMonState_Suprise_Attack.h"

#include "NorMonState/NorMonState_TakeExecution.h"
#include "NorMonState/NorMonState_Idle2Fight.h"


#include "NorMonster.h"